# Generated by Django 3.0.6 on 2020-06-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200609_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_buyer',
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
