# Generated by Django 3.0.6 on 2020-06-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='plant_price',
            field=models.IntegerField(default=0),
        ),
    ]
