# Generated by Django 3.0.6 on 2020-06-10 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nursery', '0001_initial'),
        ('core', '0003_auto_20200610_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.BuyerProfile')),
                ('plants', models.ManyToManyField(to='nursery.Plants')),
            ],
        ),
    ]
