# Generated by Django 3.0.6 on 2020-06-12 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200610_1654'),
        ('nursery', '0001_initial'),
        ('buyer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price_op', models.IntegerField(default=0)),
                ('buyer_op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BuyerProfile')),
                ('plants_op', models.ManyToManyField(to='nursery.Plants')),
            ],
        ),
    ]
